services:
  app:
    image: mysociety/climate_scorecard_data_2022:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/workspaces/climate_scorecard_data_2022/