title: Climate Scorecard Data 2022
description: >
  Data and notebooks for Council Climate Scorecard Data 2022
baseurl: "/climate_scorecard_data_2022"
url: "https://mysociety.github.io"


collections:
  datasets:
    output: true
    permalink: /datasets/:name/
  downloads:
    output: true
    permalink: /downloads/:name/


#  download_gate_type, require form submission before download. soft, present at same time but do not put up a barrier.

defaults:
  - scope:
      path: ""
      type: datasets
    values:
      layout: datasets/dataset
  - scope:
      path: ""
      type: downloads
    values:
      download_gate_type: soft
      download_form_header: Can you help us with funding by telling us more about yourself?
      download_survey: 6876792/Data-usage
      layout: datasets/download

# Build settings
description: Data behind Climate Emergency's 2022 Climate Scorecards

plugins:
  - jekyll-feed

sass:
    sass_dir: 
    load_paths:
        - theme/sass
        - sass  


# Exclude these files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .travis.yml
  - node_modules
  - scripts/src
  - package.json
  - webpack.config.js
  - README.md
  - LICENSE
